# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=128)),
                ('phone_num', models.DecimalField(decimal_places=0, max_digits=15)),
            ],
        ),
    ]
