# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-06 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Зворотній звязок', 'verbose_name_plural': 'Зворотній звязок'},
        ),
        migrations.AddField(
            model_name='contact',
            name='how_much',
            field=models.CharField(default='', max_length=3, verbose_name='Кількість людей'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата відправки'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=1000, verbose_name='Повідомлення'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=30, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='contact',
            name='second_name',
            field=models.CharField(max_length=30, verbose_name='Прізвище'),
        ),
    ]
