# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-21 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180819_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinorder',
            options={'verbose_name': 'Товар в замовлені', 'verbose_name_plural': 'Товари в замолені'},
        ),
    ]
