# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-29 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20180826_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_discount',
            field=models.IntegerField(default=0),
        ),
    ]
