# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-29 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_price_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_discount',
            new_name='price_discoun',
        ),
    ]
