# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-30 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20180929_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_discoun',
        ),
        migrations.AddField(
            model_name='product',
            name='price_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
